steps:
  - command: .buildkite/scripts/pipelines/security_solution_quality_gate/create_docker_image.sh
    label: Build kibana image
    key: build_image
    agents:
      queue: n2-16-spot
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: "-1"
          limit: 3

  - command: .buildkite/scripts/pipelines/security_solution_quality_gate/upload_runtime_info.sh
    label: "Upload runtime info"
    key: upload_runtime_info
    depends_on: build_image
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 300
    retry:
      automatic:
        - exit_status: "*"
          limit: 1
        - exit_status: "-1"
          limit: 2

  - label: Running exception_workflows:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh exception_workflows:qa:serverless
    key: exception_workflows:qa:serverless
    depends_on: build_image
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running exception_operators_date_numeric_types:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh exception_operators_date_numeric_types:qa:serverless
    key: exception_operators_date_numeric_types:qa:serverless
    depends_on: build_image
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running exception_operators_keyword:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh exception_operators_keyword:qa:serverless
    key: exception_operators_keyword:qa:serverless
    depends_on: build_image
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running exception_operators_ips:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh exception_operators_ips:qa:serverless
    depends_on: build_image
    key: exception_operators_ips:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running exception_operators_long:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh exception_operators_long:qa:serverless
    depends_on: build_image
    key: exception_operators_long:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running exception_operators_text:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh exception_operators_text:qa:serverless
    depends_on: build_image
    key: exception_operators_text:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running rule_creation:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh rule_creation:qa:serverless
    depends_on: build_image
    key: rule_creation:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running actions:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh actions:qa:serverless
    depends_on: build_image
    key: actions:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running entity_analytics:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh entity_analytics:qa:serverless
    depends_on: build_image
    key: entity_analytics:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running prebuilt_rules_management:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh prebuilt_rules_management:qa:serverless
    depends_on: build_image
    key: prebuilt_rules_management:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running prebuilt_rules_bundled_prebuilt_rules_package:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh prebuilt_rules_bundled_prebuilt_rules_package:qa:serverless
    depends_on: build_image
    key: prebuilt_rules_bundled_prebuilt_rules_package:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running prebuilt_rules_large_prebuilt_rules_package:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh prebuilt_rules_large_prebuilt_rules_package:qa:serverless
    depends_on: build_image
    key: prebuilt_rules_large_prebuilt_rules_package:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running prebuilt_rules_update_prebuilt_rules_package:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh prebuilt_rules_update_prebuilt_rules_package:qa:serverless
    depends_on: build_image
    key: prebuilt_rules_update_prebuilt_rules_package:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running rule_execution_logic:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh rule_execution_logic:qa:serverless
    depends_on: build_image
    key: rule_execution_logic:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running user_roles:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh user_roles:qa:serverless
    depends_on: build_image
    key: user_roles:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2

  - label: Running telemetry:qa:serverless
    command: .buildkite/scripts/pipelines/security_solution_quality_gate/api-integration-tests.sh telemetry:qa:serverless
    depends_on: build_image
    key: telemetry:qa:serverless
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: "1"
          limit: 2
        - exit_status: "-1"
          limit: 2
