steps:
  - command: .buildkite/scripts/pipelines/security_solution_quality_gate/create_docker_image.sh
    label: Build kibana image
    key: build_image
    agents:
      queue: n2-16-spot
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: "-1"
          limit: 3

  - command: .buildkite/scripts/pipelines/security_solution_quality_gate/upload_runtime_info.sh
    label: "Upload runtime info"
    key: upload_runtime_info
    depends_on: build_image
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 300
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - command: .buildkite/scripts/pipelines/security_solution_quality_gate/security_solution_cypress/mki_security_solution_cypress.sh cypress:run:qa:serverless
    label: "Serverless MKI QA Security Cypress Tests"
    depends_on: build_image
    agents:
      queue: n2-4-spot
    # TODO : Revise the timeout when the pipeline will be officially integrated with the quality gate.
    timeout_in_minutes: 300
    parallelism: 6
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - command: .buildkite/scripts/pipelines/security_solution_quality_gate/security_solution_cypress/mki_security_solution_cypress.sh cypress:run:qa:serverless:explore
    label: "Serverless MKI QA Explore - Security Solution Cypress Tests"
    depends_on: build_image
    agents:
      queue: n2-4-spot
    # TODO : Revise the timeout when the pipeline will be officially integrated with the quality gate.
    timeout_in_minutes: 300
    parallelism: 4
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - command: .buildkite/scripts/pipelines/security_solution_quality_gate/security_solution_cypress/mki_security_solution_cypress.sh cypress:run:qa:serverless:investigations
    label: "Serverless MKI QA Investigations - Security Solution Cypress Tests"
    depends_on: build_image
    agents:
      queue: n2-4-spot
    # TODO : Revise the timeout when the pipeline will be officially integrated with the quality gate.
    timeout_in_minutes: 300
    parallelism: 8
    retry:
      automatic:
        - exit_status: "*"
          limit: 1
